### PR TITLE
feat: added change-password request added in strapi v. 4.3.3

### LINKED ISSUE #141: Change password
### Summary
In Strapi there is an change-password endpoint in auth.

### Why is it needed?
To reflect the Strapi api.

### Suggested solution(s)
An method like changePassword should be added.

### PR DESCRIPTION
**Pull request by AnnikenYT**
## Types of changes

- [ ] Bug fix (a non-breaking change which fixes an issue)
- [x] New feature (a non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Other changes (could be a refactor, documentation change ect...)

## Description

Resolves #141 

## Checklist:

- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have added tests to cover my changes (if not applicable, please state why)

### CODE REVIEW

**Comment by AnnikenYT** [comment]
missing 3 commits, need to figure out how to push from codespaces to other repo haha

**Comment by AnnikenYT** [comment]
Workflow is failing, see #144

**Comment by Stun3R** [comment]
Hey 👋🏼 Sorry for late reply, I've had some changes in my life that have taken me away from this package for a while.

Are you still up to end this PR? If so could you please rebase on `develop` branch pls 👼🏼

**Comment by AnnikenYT** [comment]
Hiya,
Sure, it's pretty much ready I think, just need to rerun the ci.
I'll check if everything still works when I get home. :)

**Comment by Stun3R** [comment]
@AnnikenYT Can you rebase this PR on `develop` as it is the default branch now and some changes has been made?

**Comment by AnnikenYT** [comment]
Changed the base to develop, but I don't have write access to this repo. You should be able to rebase it from here, no?

**Review by Stun3R — APPROVED** [review]

**Pull request merged**
